# Generated by Django 4.2.6 on 2023-10-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_cartitem_delete_productsincardquantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='title',
            field=models.CharField(default='Корзина', max_length=255),
        ),
    ]
